# Generated by Django 4.0.3 on 2022-04-19 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=14)),
                ('resault', models.CharField(max_length=100)),
                ('response_time', models.FloatField()),
                ('response_state', models.BooleanField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.cities')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
