# Generated by Django 4.0.3 on 2022-04-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_logs_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.cities'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='response_state',
            field=models.BooleanField(default=False),
        ),
    ]
